language: php
php:
    - '8.0'

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: xenial

before_install:
  - sudo systemctl unmask mysql.service
  - sudo service mysql start
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('test'), User='test' where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u test -ptest
  - sudo service mysql restart

before_script:
    - composer install

script:
    - composer validate --strict
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/phpcs src/ tests/

cache:
  directories:
    - $HOME/.composer/cache
